---

- name: Gather facts
  setup:

- name: Install libselinux-python package for 'copy' task
  package:
    name: libselinux-python
    state: present
  become: true
  when: ansible_os_family == "RedHat"
